#!/usr/bin/env bash
# Shared fitment credential helpers (sourced, not executed).
set -euo pipefail

FITMENT_ROOT="${FITMENT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
FITMENT_ENV_FILE="${FITMENT_ENV_FILE:-$FITMENT_ROOT/.env.fitment.local}"
FITMENT_STORE="${SHOPIFY_STORE:-tracktech-530.myshopify.com}"
FITMENT_PROJECT_REF="${SUPABASE_PROJECT_REF:-tcykyktvdlsbscrsbjyt}"
FITMENT_CLIENT_ID="${SHOPIFY_CLIENT_ID:-d9f03e5dc828e0859a32c7036a382689}"
export SUPABASE_URL="${SUPABASE_URL:-https://${FITMENT_PROJECT_REF}.supabase.co}"

load_fitment_env() {
  if [[ -f "$FITMENT_ENV_FILE" ]]; then
    set -a
    # shellcheck source=/dev/null
    source "$FITMENT_ENV_FILE"
    set +a
  fi
}

# Parse service_role JWT from `supabase projects api-keys` stdout (tolerates npm noise).
extract_service_role_key() {
  python3 -c "
import json, re, sys

raw = sys.stdin.read()
if not raw.strip():
    sys.exit(1)

def pick_key(data):
    keys = data.get('keys') or []
    for k in keys:
        if k.get('name') == 'service_role' or k.get('id') == 'service_role':
            api_key = k.get('api_key') or ''
            if api_key and '···' not in api_key and '...' not in api_key:
                return api_key
    for k in keys:
        tmpl = k.get('secret_jwt_template') or {}
        if tmpl.get('role') == 'service_role':
            api_key = k.get('api_key') or ''
            if api_key and '···' not in api_key and '...' not in api_key:
                return api_key
    return None

# Prefer explicit JSON lines, then fall back to first {...} blob in mixed output.
candidates = []
for line in raw.splitlines():
    line = line.strip()
    if line.startswith('{'):
        candidates.append(line)

if not candidates:
    m = re.search(r'\{.*\}', raw, re.DOTALL)
    if m:
        candidates.append(m.group(0))

for blob in reversed(candidates):
    try:
        data = json.loads(blob)
    except json.JSONDecodeError:
        continue
    key = pick_key(data)
    if key:
        print(key)
        sys.exit(0)

sys.exit(1)
"
}

validate_service_role_key() {
  local key="${1:-}"
  [[ -n "$key" ]] || return 1
  python3 -c "
import base64, json, sys

key = sys.argv[1]
if key.startswith('sb_secret_'):
    sys.exit(0)
parts = key.split('.')
if len(parts) != 3:
    sys.exit(1)
payload = parts[1] + '=' * (-len(parts[1]) % 4)
try:
    data = json.loads(base64.urlsafe_b64decode(payload))
except Exception:
    sys.exit(1)
sys.exit(0 if data.get('role') == 'service_role' else 1)
" "$key"
}

fetch_supabase_api_keys() {
  local cli_err
  cli_err=$(mktemp)
  # Keep stderr separate; npm progress/warnings must not pollute JSON on stdout.
  if ! NPM_CONFIG_UPDATE_NOTIFIER=false npx --yes supabase projects api-keys \
      --project-ref "$FITMENT_PROJECT_REF" \
      --output-format json 2>"$cli_err"; then
    if grep -qiE 'not logged in|access token|login required|unauthorized|401|403|invalid token|expired' "$cli_err" 2>/dev/null; then
      echo "Supabase CLI session expired — run: npx supabase login" >&2
    elif [[ -s "$cli_err" ]]; then
      echo "supabase projects api-keys failed: $(tr '\n' ' ' < "$cli_err")" >&2
    fi
    rm -f "$cli_err"
    return 1
  fi
  rm -f "$cli_err"
}

load_service_role_key() {
  if [[ -n "${SUPABASE_SERVICE_ROLE_KEY:-}" ]]; then
    validate_service_role_key "$SUPABASE_SERVICE_ROLE_KEY" && return 0
    unset SUPABASE_SERVICE_ROLE_KEY
  fi

  local cli_out
  if ! cli_out=$(fetch_supabase_api_keys); then
    return 1
  fi

  if ! SUPABASE_SERVICE_ROLE_KEY=$(printf '%s\n' "$cli_out" | extract_service_role_key); then
    echo "Could not parse service_role key from Supabase CLI output." >&2
    echo "  Fix: npx supabase login  then re-run: ./scripts/fitment doctor" >&2
    return 1
  fi

  if ! validate_service_role_key "$SUPABASE_SERVICE_ROLE_KEY"; then
    echo "Parsed key does not look like a service_role JWT." >&2
    echo "  Fix: npx supabase login  then re-run: ./scripts/fitment doctor" >&2
    unset SUPABASE_SERVICE_ROLE_KEY
    return 1
  fi

  export SUPABASE_SERVICE_ROLE_KEY
  return 0
}

write_fitment_env_file() {
  local token="${1:-}"
  local service_key="${2:-${SUPABASE_SERVICE_ROLE_KEY:-}}"
  {
    echo "# Generated by fitment setup/bootstrap — do not commit"
    echo "SHOPIFY_STORE_DOMAIN=${FITMENT_STORE}"
    if [[ -n "$token" ]]; then
      echo "SHOPIFY_ADMIN_TOKEN=${token}"
    else
      echo "# SHOPIFY_ADMIN_TOKEN=  # optional; sync can use shopify store execute"
    fi
    echo "SUPABASE_URL=${SUPABASE_URL}"
    if [[ -n "$service_key" ]]; then
      echo "SUPABASE_SERVICE_ROLE_KEY=${service_key}"
    else
      echo "# SUPABASE_SERVICE_ROLE_KEY=  # run: npx supabase login && ./scripts/fitment bootstrap"
    fi
  } > "$FITMENT_ENV_FILE"
  chmod 600 "$FITMENT_ENV_FILE"
}
