#!/usr/bin/env bash
# One-time setup: get Shopify token → save in Supabase for sync-product-fitments
set -euo pipefail

STORE="tracktech-530.myshopify.com"
CLIENT_ID="d9f03e5dc828e0859a32c7036a382689"
PROJECT_REF="tcykyktvdlsbscrsbjyt"

echo "=== Heavy Iron: Supabase + Shopify sync setup ==="
echo ""
echo "You need your HEAVY IRON app Secret from:"
echo "  https://dev.shopify.com → Apps → HEAVY IRON → Settings → Credentials"
echo "  Click the eye icon next to Secret, then Copy."
echo ""
read -rsp "Paste Client Secret here (hidden): " CLIENT_SECRET
echo ""
echo ""

if [[ -z "${CLIENT_SECRET}" ]]; then
  echo "Error: secret was empty."
  exit 1
fi

echo "Getting access token from Shopify..."
RESP=$(curl -s -X POST "https://${STORE}/admin/oauth/access_token" \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "grant_type=client_credentials" \
  -d "client_id=${CLIENT_ID}" \
  -d "client_secret=${CLIENT_SECRET}")

TOKEN=$(echo "$RESP" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('access_token',''))" 2>/dev/null || true)

if [[ -z "${TOKEN}" ]]; then
  echo "Failed to get token. Shopify returned:"
  echo "$RESP"
  echo ""
  echo "Fix: Install HEAVY IRON on tracktech-530 in Dev Dashboard first."
  exit 1
fi

echo "Got token (starts with ${TOKEN:0:6}...)"
echo ""
echo "Saving to Supabase (you may need: npx supabase login)..."
npx supabase secrets set \
  SHOPIFY_STORE_DOMAIN="${STORE}" \
  SHOPIFY_ADMIN_TOKEN="${TOKEN}" \
  --project-ref "${PROJECT_REF}"

ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.fitment.local"
SERVICE_KEY=""
if CLI_OUT=$(npx supabase projects api-keys --project-ref "$PROJECT_REF" 2>/dev/null); then
  SERVICE_KEY=$(printf '%s\n' "$CLI_OUT" | python3 -c "
import sys, json
lines = [l.strip() for l in sys.stdin.read().splitlines() if l.strip().startswith('{')]
if not lines: sys.exit(1)
data = json.loads(lines[-1])
for k in data.get('keys', []):
    if k.get('name') == 'service_role' or k.get('id') == 'service_role':
        print(k['api_key']); break
else: sys.exit(1)
" 2>/dev/null) || true
fi

{
  echo "# Generated by setup-supabase-shopify-secrets.sh — do not commit"
  echo "SHOPIFY_STORE_DOMAIN=${STORE}"
  echo "SHOPIFY_ADMIN_TOKEN=${TOKEN}"
  echo "SUPABASE_URL=https://${PROJECT_REF}.supabase.co"
  if [[ -n "$SERVICE_KEY" ]]; then
    echo "SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}"
  else
    echo "# SUPABASE_SERVICE_ROLE_KEY=  # run: npx supabase login && re-run setup"
  fi
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"
echo "Wrote local credentials → .env.fitment.local (gitignored)"

echo ""
echo "Testing dry-run sync..."
curl -s -X POST "https://${PROJECT_REF}.supabase.co/functions/v1/sync-product-fitments" \
  -H "Content-Type: application/json" \
  -d '{"dry_run":true,"limit":3}'
echo ""
echo ""
echo "Done. Next: ./scripts/fitment sync"
